name: api_client
description: The interface and models for an API providing access to monitoring data.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  http:

dev_dependencies:
  build_runner: 
  test:
  mockito: